package com.danielkkrafft.wilddungeons.dungeon.registries;

import com.danielkkrafft.wilddungeons.dungeon.DungeonRegistration;
import com.danielkkrafft.wilddungeons.dungeon.components.template.DungeonRoomTemplate;
import com.danielkkrafft.wilddungeons.util.WeightedPool;

import static com.danielkkrafft.wilddungeons.dungeon.registries.DungeonRoomRegistry.*;

public class DungeonRoomPoolRegistry {
    public static final DungeonRegistration.DungeonComponentRegistry<WeightedPool<DungeonRoomTemplate>> ROOM_POOL_REGISTRY = new DungeonRegistration.DungeonComponentRegistry<>();
    
    public static final WeightedPool<DungeonRoomTemplate> SMALL_ROOM_POOL = create("SMALL_ROOM_POOL")
            .add(SMALL_1, 1)
            .add(SMALL_2, 1)
            .add(SMALL_3, 1)
            .add(SMALL_4, 1)
            .add(SMALL_5, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> MEDIUM_ROOM_POOL = create("MEDIUM_ROOM_POOL")
            .add(MEDIUM_1, 1)
            .add(MEDIUM_2, 1)
            .add(MEDIUM_3, 1)
            .add(MEDIUM_4, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> SECRET_POOL = create("SECRET_POOL")
            .add(SECRET_1, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> SHOP_POOL = create("SHOP_POOL")
            .add(SHOP_1, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> LOOT_POOL = create("LOOT_POOL")
            .add(LOOT_1, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> REST_POOL = create("REST_POOL")
            .add(REST, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> PARKOUR_POOL = create("PARKOUR_POOL")
            .add(PARKOUR, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> COMBAT_ROOM_POOL = create("COMBAT_ROOM_POOL")
            .add(LARGE_1, 1);

    public static final WeightedPool<DungeonRoomTemplate> OVERWORLD_SPRAWL_ROOM_POOL = create("OVERWORLD_SPRAWL_ROOM_POOL")
            .add(OVERWORLD_BASIC_1, 4)
            .add(OVERWORLD_BASIC_2, 4)
            .add(OVERWORLD_BASIC_3, 1)
            .add(OVERWORLD_BASIC_4, 3)
            .add(OVERWORLD_BASIC_5, 4)
            .add(OVERWORLD_BASIC_6, 3)
            .add(OVERWORLD_BASIC_7, 3)
            .add(OVERWORLD_COMBAT_1, 2)
            .add(OVERWORLD_COMBAT_2, 2)
            .add(OVERWORLD_COMBAT_3, 2)
            .add(OVERWORLD_COMBAT_4, 2)
            .add(OVERWORLD_CHEST_ROOM, 2)
            .add(OVERWORLD_STAIRCASE, 1)
            .add(OVERWORLD_STAIRWAY_1, 1)
            .add(OVERWORLD_HALLWAY_1, 2)
            .add(OVERWORLD_HALLWAY_2, 1)
            .add(OVERWORLD_CRAFTING_ROOM, 1)
            .add(OVERWORLD_PARKOUR, 1)
            .add(OVERWORLD_SECRET, 1)
            .add(OVERWORLD_SMELTER_ROOM, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> OVERWORLD_SPACER_ROOM_POOL = create("OVERWORLD_SPACER_ROOM_POOL")
            .add(OVERWORLD_STAIRWAY_1, 1)
            .add(OVERWORLD_HALLWAY_1, 3)
            .add(OVERWORLD_HALLWAY_2, 2);
    
    public static final WeightedPool<DungeonRoomTemplate> OVERWORLD_REST_ROOM_POOL = create("OVERWORLD_REST_ROOM_POOL")
            .add(OVERWORLD_REST_ROOM, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> OVERWORLD_LOOT_ROOM_POOL = create("OVERWORLD_LOOT_ROOM_POOL")
            .add(OVERWORLD_FREE_PERK, 1)
            .add(OVERWORLD_DOUBLE_LOOT, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> OVERWORLD_SHOP_ROOM_POOL = create("OVERWORLD_SHOP_ROOM_POOL")
            .add(OVERWORLD_SHOP_ROOM, 1);

    public static final WeightedPool<DungeonRoomTemplate> PIGLIN_FACTORY_CAVE_SPRAWL_ROOM_POOL = create("PIGLIN_FACTORY_CAVE_SPRAWL_ROOM_POOL")
            .add(NETHER_CAVE_SPRAWL_1, 1)
            .add(NETHER_CAVE_SPRAWL_2, 1)
            .add(NETHER_CAVE_COMBAT_2, 1)
            .add(NETHER_CAVE_SPRAWL_3, 1)
            .add(NETHER_CAVE_SPRAWL_4, 1)
            .add(NETHER_CAVE_SPRAWL_5, 1)
            .add(NETHER_CAVE_SPRAWL_6, 1)
            .add(NETHER_CAVE_SPRAWL_7, 1)
            .add(NETHER_CAVE_COMBAT_1, 1)
            .add(NETHER_CAVE_SPRAWL_8, 1)
            .add(NETHER_CAVE_SPRAWL_9, 1)
            .add(NETHER_CAVE_SPRAWL_10, 1)
            .add(NETHER_CAVE_SPRAWL_11, 1)
            .add(NETHER_CAVE_SPRAWL_12, 1)
            .add(NETHER_CAVE_SPRAWL_13, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> PIGLIN_FACTORY_PIPEWORKS_ROOM_POOL = create("PIGLIN_FACTORY_PIPEWORKS_ROOM_POOL")
            .add(NETHER_PIPEWORKS_0, 1)
            .add(NETHER_PIPEWORKS_1, 1)
            .add(NETHER_PIPEWORKS_2, 1)
            .add(NETHER_PIPEWORKS_3, 1)
            .add(NETHER_PIPEWORKS_4, 1)
            .add(NETHER_PIPEWORKS_5, 1)
            .add(NETHER_PIPEWORKS_6, 1)
            .add(NETHER_PIPEWORKS_LAVAFALLS, 1)
            .add(NETHER_PIPEWORKS_BREAKOUT_ROOM, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> PIGLIN_FACTORY_SPRAWL_ROOM_POOL = create("PIGLIN_FACTORY_SPRAWL_ROOM_POOL")
            .add(NETHER_FACTORY_SPRAWL_1, 1)
            .add(NETHER_FACTORY_SPRAWL_2, 1)
            .add(NETHER_FACTORY_SPRAWL_3, 1)
            .add(NETHER_FACTORY_SPRAWL_4, 1)
            .add(NETHER_FACTORY_SPRAWL_5, 1)
            .add(NETHER_FACTORY_SPRAWL_6, 1)
            .add(NETHER_FACTORY_RAIL_1, 1)
            .add(NETHER_FACTORY_RAIL_TRANSITION, 1)
            .add(NETHER_FACTORY_COMBAT_1, 1)
            .add(NETHER_FACTORY_COMBAT_2, 1)
            .add(NETHER_FACTORY_PARKOUR_1, 1)
            .add(NETHER_FACTORY_PARKOUR_2, 1)
            .add(NETHER_FACTORY_REST_1, 1)
            .add(NETHER_FACTORY_TRAP_1, 1);
    
    public static final WeightedPool<DungeonRoomTemplate> PIGLIN_FACTORY_SHOP_ROOM_POOL = create("PIGLIN_FACTORY_SHOP_ROOM_POOL")
            .add(NETHER_FACTORY_SHOP_1, 1)
            .add(NETHER_FACTORY_SHOP_2, 1);

    public static final WeightedPool<DungeonRoomTemplate> VILLAGE_SEWER_POOL = create("VILLAGE_SEWER_POOL")
            .add(VILLAGE_SEWER_1, 1)
            .add(VILLAGE_SEWER_2, 1)
            .add(VILLAGE_SEWER_3, 1)
            .add(VILLAGE_SEWER_4, 1)
            .add(VILLAGE_SEWER_5, 1)
            .add(VILLAGE_SEWER_6, 1)
            .add(VILLAGE_SEWER_7, 1)
            .add(VILLAGE_SEWER_8, 1)
            .add(VILLAGE_SEWER_9, 1)
            .add(VILLAGE_SEWER_10, 1)
            .add(VILLAGE_SEWER_11, 1)
            .add(VILLAGE_SEWER_12, 1)
            .add(VILLAGE_SEWER_13, 1)
            .add(VILLAGE_SEWER_CHESTCAP, 1)
            .add(VILLAGE_SEWER_ELEVATOR, 1)
            .add(VILLAGE_SEWER_DEELEVATOR, 1)
            .add(VILLAGE_SEWER_12_COMBAT, 2);
    
    public static final WeightedPool<DungeonRoomTemplate> VILLAGE_WIDE_PATH_POOL = create("VILLAGE_WIDE_PATH_POOL")
            .add(VILLAGE_METRO_WIDE_CROSSROADS,2)
//            .add(VILLAGE_METRO_WIDE_STAIRS,1)//todo way to handle vertical gaps
            .add(VILLAGE_METRO_WIDE_PATH, 10);

    public static final WeightedPool<DungeonRoomTemplate> VILLAGE_MEDIUM_PLOTS = create("VILLAGE_MEDIUM_PLOTS")
            .add(VILLAGE_METRO_CHURCH,1)
            .add(VILLAGE_METRO_DORM_TOWER,1)
            .add(VILLAGE_METRO_ILLAGER_TOWER,1)
            .add(VILLAGE_METRO_LIBRARY,1)
            .add(VILLAGE_METRO_LUMBERYARD,1)
            .add(VILLAGE_METRO_MED_CROSSROAD,1)
            .add(VILLAGE_METRO_SMITHERY,1)
            .add(VILLAGE_METRO_TANNERY,1)
            .add(VILLAGE_METRO_VERTICAL_FARM,1)
            .add(VILLAGE_METRO_COTTAGE,1)
            .add(VILLAGE_METRO_AWSEME_MED_1,1)
            .add(VILLAGE_METRO_AWSEME_MED_2,1)
            .add(VILLAGE_METRO_AWSEME_MED_3,1)
            .add(VILLAGE_METRO_AWSEME_MED_4,1)
            .add(VILLAGE_METRO_AWSEME_MED_5,1)
            .add(VILLAGE_METRO_AWSEME_MED_5B,1)
            .add(VILLAGE_METRO_AWSEME_MED_6,1)
            .add(VILLAGE_METRO_AWSEME_MED_7,1)
            .add(VILLAGE_METRO_AWSEME_MED_8,1)
            .add(VILLAGE_METRO_AWSEME_MED_9,1)
            .add(VILLAGE_METRO_AWSEME_MED_10,1)
            .add(VILLAGE_METRO_AWSEME_MED_11,1)
            .add(VILLAGE_METRO_AWSEME_MED_12,1)
            .add(VILLAGE_METRO_AWSEME_MED_13,1)
            .add(VILLAGE_METRO_AWSEME_MED_14,1)
            .add(VILLAGE_METRO_AWSEME_MED_15,1)
            .add(VILLAGE_METRO_AWSEME_MED_16,1)
            .add(VILLAGE_METRO_AWSEME_MED_17,1)
            .add(VILLAGE_METRO_AWSEME_MED_18,1)
            .add(VILLAGE_METRO_AWSEME_MED_19,1)
            .add(VILLAGE_METRO_AWSEME_MED_20,1)
            .add(VILLAGE_METRO_AWSEME_MED_CAVE,1)
            .add(VILLAGE_METRO_AWSEME_MED_FOUNTAIN,1)
            .add(VILLAGE_METRO_AWSEME_MED_HOLLOW_HILL,1)
            .add(VILLAGE_METRO_AWSEME_MED_QUARRY,1)
            .add(VILLAGE_METRO_AWSEME_MED_STONECUTTER,1)
            .add(VILLAGE_METRO_AIYQE_MED_BONFIRE,1)
            .add(VILLAGE_METRO_AIYQE_MED_DEEPSLATE_MINE,1)
            .add(VILLAGE_METRO_AIYQE_MED_SALMON_BRIDGE,1)
            .add(VILLAGE_METRO_AIYQE_MED_TRADING_POST,1)
            .add(VILLAGE_METRO_ARCANIST_MED_DEAD_TREE,1)
            .add(VILLAGE_METRO_ARCANIST_MED_FISHING_POND,1)
            .add(VILLAGE_METRO_ARCANIST_MED_SAFE_HOUSE,1)
            .add(VILLAGE_METRO_ARCANIST_MED_WITCH_TOWER,1)
            .add(VILLAGE_METRO_CHLTER121_MED_BEEKEEPERS,1)
            .add(VILLAGE_METRO_CHLTER121_MED_FOOD_COURT,1)
            .add(VILLAGE_METRO_CHLTER121_MED_FOUR_PARKOUR,1)
            .add(VILLAGE_METRO_CHLTER121_MED_GRAVEYARD,1)
            .add(VILLAGE_METRO_CHLTER121_MED_GRAVEYARD_BROKEN,1)
            .add(VILLAGE_METRO_CHLTER121_MED_HEDGE_MAZE,1)
            .add(VILLAGE_METRO_CHLTER121_MED_HOUSE,1)
            .add(VILLAGE_METRO_CHLTER121_MED_HOUSE_ARCHERY,1)
            .add(VILLAGE_METRO_CHLTER121_MED_HOUSE_CHERRY,1)
            .add(VILLAGE_METRO_CHLTER121_MED_HOUSE_CONSTRUCTION,1)
            .add(VILLAGE_METRO_CHLTER121_MED_HOUSE_REEDS,1)
            .add(VILLAGE_METRO_CHLTER121_MED_MARKET_STALLS,1)
            .add(VILLAGE_METRO_CHLTER121_MED_PLAZA,1)
            .add(VILLAGE_METRO_CHLTER121_MED_RUINED_HOUSE_1,1)
            .add(VILLAGE_METRO_CHLTER121_MED_RUINED_HOUSE_2,1)
            .add(VILLAGE_METRO_ENDER_MED_BRICK_TOWER,1)
            .add(VILLAGE_METRO_ENDER_MED_FARM,1)
            .add(VILLAGE_METRO_ENDER_MED_FOUNTAIN,1)
            .add(VILLAGE_METRO_ENDER_MED_HOUSE_1,1)
            .add(VILLAGE_METRO_ENDER_MED_HOUSE_2,1)
            .add(VILLAGE_METRO_ENDER_MED_HOUSE_3,1)
            .add(VILLAGE_METRO_ENDER_MED_HOUSE_4,1)
            .add(VILLAGE_METRO_ENDER_MED_HOUSE_5,1)
            .add(VILLAGE_METRO_ENDER_MED_HOUSE_6,1)
            .add(VILLAGE_METRO_ENDER_MED_MARKET_STALLS,1)
            .add(VILLAGE_METRO_ENDER_MED_OASIS,1)
            .add(VILLAGE_METRO_ENDER_MED_PARKOUR,1)
            .add(VILLAGE_METRO_ENDER_MED_POND,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_CHURCH,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_CRYSTAL_TOWER,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_DUPLEX,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_EMERALD_ARCH,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_FISHING_POND,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_GARDEN,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_GRAVEYARD,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_HOUSE_1,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_HOUSE_2,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_HOUSE_3,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_HOUSE_4,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_HOUSE_FARM,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_HOUSE_FARM_RUINED,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_LIBRARY,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_MARKET_STALLS,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_PLAZA,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_REDSTONE_SHOP,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_SMITHERY,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_STABLES,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_TOWER,1)
            .add(VILLAGE_METRO_FLYINGNOKK_MED_WELL_RUINED,1)
            ;

    public static final WeightedPool<DungeonRoomTemplate> VILLAGE_SMALL_PLOTS = create("VILLAGE_SMALL_PLOTS")
            .add(VILLAGE_METRO_CROSS,1)
            .add(VILLAGE_METRO_FOUNTAIN,1)
            .add(VILLAGE_METRO_HOME,4)
            .add(VILLAGE_METRO_TREE,4)
            .add(VILLAGE_METRO_AWSEME_SML_ARCH,1)
            .add(VILLAGE_METRO_AWSEME_SML_CART,1)
            .add(VILLAGE_METRO_AWSEME_SML_CORNER_ARCH,1)
            .add(VILLAGE_METRO_AWSEME_SML_FOUR_ARCH,1)
            .add(VILLAGE_METRO_AWSEME_SML_TRI_ARCH,1)
            .add(VILLAGE_METRO_AWSEME_SML_TRI_FOUNTAIN,1)
            .add(VILLAGE_METRO_AIYQE_SML_HALLOW_FARM,1)
            .add(VILLAGE_METRO_AIYQE_SML_HALLOW_TREE,1)
            .add(VILLAGE_METRO_AIYQE_SML_REST_HUT,1)
            .add(VILLAGE_METRO_AIYQE_SML_TINYHOME,1)
            .add(VILLAGE_METRO_ARCANIST_SML_CARROT,1)
            .add(VILLAGE_METRO_ARCANIST_SML_CRYING_STATUE,1)
            .add(VILLAGE_METRO_ARCANIST_SML_TEMPLE,1)
            .add(VILLAGE_METRO_ARCANIST_SML_WET_CROSS,1)
            .add(VILLAGE_METRO_CHLTER121_SML_CHERRY_TREE,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_BEETROOT,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_BERRIES,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_CARROT,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_MELON,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_POTATO,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_PUMPKIN,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_SUGARCANE,1)
            .add(VILLAGE_METRO_CHLTER121_SML_FARM_WHEAT,1)
            .add(VILLAGE_METRO_CHLTER121_SML_INCINERATOR,1)
            .add(VILLAGE_METRO_CHLTER121_SML_JAIL,1)
            .add(VILLAGE_METRO_CHLTER121_SML_PLANTER_WARPED,1)
            .add(VILLAGE_METRO_CHLTER121_SML_STATUE_KNEELING,1)
            .add(VILLAGE_METRO_CHLTER121_SML_TOWER_OPEN,1)
            .add(VILLAGE_METRO_CHLTER121_SML_TOWER_OPEN_B,1)
            .add(VILLAGE_METRO_CHLTER121_SML_WELL,1)
            .add(VILLAGE_METRO_ENDER_SML_DEBRIS,1)
            .add(VILLAGE_METRO_ENDER_SML_FARM,1)
            .add(VILLAGE_METRO_ENDER_SML_FOUNTAIN,1)
            .add(VILLAGE_METRO_ENDER_SML_HOUSE_1,1)
            .add(VILLAGE_METRO_ENDER_SML_HOUSE_2,1)
            .add(VILLAGE_METRO_ENDER_SML_HOUSE_3,1)
            .add(VILLAGE_METRO_ENDER_SML_HOUSE_RUINED,1)
            .add(VILLAGE_METRO_ENDER_SML_MARKET_STALL,1)
            .add(VILLAGE_METRO_ENDER_SML_TENT,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_BEES,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_BELL_TOWER,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_CART,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_FARM_BEETROOT,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_FARM_CARROT,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_FARM_POTATO,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_FOUNTAIN,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_HEDGES,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_HOUSE_1,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_HOUSE_2,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_HOUSE_3,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_PATH_HEDGES,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_RUINS,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_SIDEWALK,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_SIDEWALK_2,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_SMELTER,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_STATUE,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_TARGETS,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_TREE,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_TREE_2,1)
            .add(VILLAGE_METRO_FLYINGNOKK_SML_WHEAT_PATH,1)
            ;

    public static final WeightedPool<DungeonRoomTemplate> VILLAGE_TOWER_FLOORS = create("VILLAGE_TOWER_FLOORS")
            .add(VILLAGE_METRO_CHLTER121_TWR_CUBICLES,1)
            .add(VILLAGE_METRO_CHLTER121_TWR_LIBRARY,1)
            .add(VILLAGE_METRO_CHLTER121_TWR_SEVERANCE,1)
            .add(VILLAGE_METRO_FLYINGNOKK_TWR_SEVERANCE_HALLS,1)
            .add(VILLAGE_METRO_FLYINGNOKK_TWR_JAIL,1)
            .add(VILLAGE_METRO_FLYINGNOKK_TWR_LOBBY,1)
            .add(VILLAGE_METRO_FLYINGNOKK_TWR_VAULT,1)
            .add(VILLAGE_METRO_MOBFIA_TWR_OFFICE,1)
            ;

    public static WeightedPool<DungeonRoomTemplate> create(String name) {
        WeightedPool<DungeonRoomTemplate> pool = new WeightedPool<DungeonRoomTemplate>()
                .setName(name);
        ROOM_POOL_REGISTRY.add(pool);
        return pool;
    }
}